name: Daily IP Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # Runs every three hours

permissions: write-all

jobs:
  update_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'

      - name: Step1 - download original csv file
        run: wget https://raw.githubusercontent.com/6Kmfi6HP/proxy_files/refs/heads/main/proxies.csv

      - name: Step2 - generate txt
        run: python 0.py

      - name: Step3 - remove old file
        run: rm proxies.csv

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Automated update IPs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
